[package]
name = "gifski_pyqt"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.17", features = ["extension-module"] }

[lib]
crate-type = ["cdylib"] # Required for Python modules
